theme: jekyll-theme-slate
title: [Out the Window:  A Crowd-Sourced Dataset for Activity Classification in Surveillance Video]
description: [Greg Castanon, Nathan Shnidman, Tim Anderson and Jeffrey Byrne Systems and Technology Research, Woburn MA]
